#.----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.
#  | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
#    | |   ________   | || |   ________   | || |      __      | || |  _______     | || |  _______     | || |     ____     | || | _____  _____ | |
#    | |  |  __   _|  | || |  |  __   _|  | || |     /  \     | || | |_   __ \    | || | |_   __ \    | || |   .'    `.   | || ||_   _||_   _|| |
#    | |  |_/  / /    | || |  |_/  / /    | || |    / /\ \    | || |   | |__) |   | || |   | |__) |   | || |  /  .--.  \  | || |  | | /\ | |  | |
#    | |     .'.' _   | || |     .'.' _   | || |   / ____ \   | || |   |  __ /    | || |   |  __ /    | || |  | |    | |  | || |  | |/  \| |  | |
#    | |   _/ /__/ |  | || |   _/ /__/ |  | || | _/ /    \ \_ | || |  _| |  \ \_  | || |  _| |  \ \_  | || |  \  `--'  /  | || |  |   /\   |  | |
#    | |  |________|  | || |  |________|  | || ||____|  |____|| || | |____| |___| | || | |____| |___| | || |   `.____.'   | || |  |__/  \__|  | |
#    | |              | || |              | || |              | || |              | || |              | || |              | || |              | |
#    | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
#    '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'

# Разработчик: Web/Java  |  Связаться: @zzrtk в Telegram

messages:
  arrow_given: "&6&l(СТРЕЛЫ) &fВам была выдана &6стрела.."
  player_not_found: "&6&l(СТРЕЛЫ) &fИгрок не &aнайден!"
  arrow_not_found: "&6&l(СТРЕЛЫ) &fСтрела не найдена в &aконфиге!"
  usage: "&6&l(СТРЕЛЫ) &fИспользование: &6/zarrows give <ник> <стрела> <кол-во>"
  arrow_given_own: "&6&l(СТРЕЛЫ) &fВы выдали стрелу &6игроку"
  no-permission: "&6&l(СТРЕЛЫ) &cНету доступа, извиняй.."

arrows:
  levetation:
    display-name: "§f§l● СТРЕЛА ПОЛЕТА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fЛевитация III §7(0:08)'
      - ''
    color: "105,105,105"
    effects:
      - "LEVITATION,160,2"
    hideattributes: true
  bog:
    display-name: "§a§l● СТРЕЛА БОГА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fСвечение §e(1:40)'
      - ' §fПрилив здоровья II §e(1:40)'
      - ' §fРегенерация I §e(1:40)'
      - ''
    color: "60,179,113"
    effects:
      - "GLOWING,2000,1"
      - "HEALTH_BOOST,2000,1"
      - "REGENERATION,2000,0"
    hideattributes: true

  yada:
    display-name: "§7§l● СТРЕЛА §7§lЯДА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fОтравление II §e(0:10)'
      - ' §fУтомленние II §e(0:10)'
      - ' §fЗамедление II §e(0:10)'
      - ''
    color: "0,0,0"
    effects:
      - "POISON,200,1"
      - "SLOW,200,1"
      - "SLOW_DIGGING,200,1"
    hideattributes: true
  toper:
    display-name: "§e§l● СТРЕЛА ТОПЕРА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fСила II §e(0:10)'
      - ' §fСкорость II §e(0:10)'
      - ''
    color: "255,240,245"
    effects:
      - "INCREASE_DAMAGE,200,1"
      - "SPEED,200,1"
    hideattributes: true

  dezorent:
    display-name: "§c§l● СТРЕЛА ДЕЗОРЕНТАЦИИ ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fСлепота III §e(0:10)'
      - ' §fСлабость I §e(0:04)'
      - ''
    color: "255,99,71"
    effects:
      - "BLINDNESS,200,2"
      - "WEAKNESS,80,0"
      - "SLOWNESS,40,0"
    hideattributes: true

  icelka:
    display-name: "§4§l● СТРЕЛА ХИЛА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fУтомление II §e(0:03)'
      - ' §fИсцеление II'
      - ''
    color: "255,127,80"
    effects:
      - "WEAKNESS,60,1"
      - "HEAL,60,1"
    hideattributes: true
  speed:
    display-name: "§9§l● СТРЕЛА БЫСТРОТЫ ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fСкорость III §e(0:10)'
      - ' §fОгнестойкость III §e(0:05)'
      - ''
    color: "135,206,235"
    effects:
      - "SPEED,200,3"
      - "FIRE_RESISTANCE,100,3"
    hideattributes: true
  jump:
    display-name: "§d§l● СТРЕЛА КРОЛИКА ●"
    lore:
      - ''
      - ' &7Эффекты:'
      - ' §fПрыгучесть IV §e(0:05)'
      - ' §fИсцеление III'
      - ''
    color: "255,0,255"
    effects:
      - "JUMP,100,4"
      - "HEAL,100,3"
    hideattributes: true




